# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  postgres:
    extends:
      file: ./icrs_database/compose.yaml
      service: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      TZ: Europe/London

  database_adapter:
    extends:
      file: ./icrs_backend/database_adapter/compose.yaml
      service: database_adapter
    environment:
      TZ: Europe/London
      ENV: dev
      PASSWORD: password
      USERNAME: user
      API_KEY: NA
    ports:
      - :8000
    volumes:
      - ./example_postgres.ini:/app/postgres.ini
      - ./example_printer_config.json:/app/printer_config.json
    depends_on:
      - postgres
  
  access-server:
    extends:
      file: ./icrs_backend/server/compose.yaml
      service: access-server
    environment:
      TZ: Europe/London
      DATABASE_ADAPTER_IP: http://database_adapter:8000
    ports:
      - :8000
    volumes:
      - ./example_postgres.ini:/app/postgres.ini
    depends_on:
      - postgres

  icrs-bot:
    extends:
      file: ./icrs_bot/registration/compose.yaml
      service: icrs-bot
    environment:
      TZ: Europe/London
      SERVER_IP: http://database_adapter:8000
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_ADAPTER_USER: user
      DATABASE_ADAPTER_PASSWORD: password
    ports:
      - :8000
    volumes:
      - ./example_postgres.ini:/app/postgres.ini
      - ./discord_settings_template.json:/app/settings.json
      - ./printer_settings_template.json:/app/printer_settings.json
    depends_on:
      - database_adapter
      - access-server


volumes:
  db-data:
    
# secrets:
#   db-password:
#     file: db/password.txt

